apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  labels:
    app: backend-api
    tier: backend
data:
  # Environment
  NODE_ENV: "production"
  PORT: "5000"

  # CORS Configuration
  CORS_ORIGIN: "https://himanshubhatt.com"
