apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-api
    tier: backend
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: backend-api
