apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: backend-api
    tier: backend
type: Opaque
data:
  # Replace <your-base64-encoded-mongodb-uri> with your actual base64 encoded MongoDB URI
  # To encode: echo -n "mongodb+srv://username:password@cluster.mongodb.net/database?retryWrites=true&w=majority" | base64
  mongodb-uri: <your-base64-encoded-mongodb-uri>
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: backend-api
    tier: backend
type: Opaque
data:
  # Replace <your-base64-encoded-jwt-secret> with your actual base64 encoded JWT secret
  # To encode: echo -n "your-jwt-secret" | base64
  jwt-secret: <your-base64-encoded-jwt-secret>
