apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  labels:
    app: backend-api
    tier: backend
type: Opaque
data:
  # Replace <your-base64-encoded-mongodb-uri> with your actual base64 encoded MongoDB URI
  # To encode: echo -n "mongodb+srv://username:password@cluster.mongodb.net/database?retryWrites=true&w=majority" | base64
  mongodb-uri: bW9uZ29kYitzcnY6Ly9oYmhhdHQwMzQ6OUMyNHVyOGFqZGMwd3JuTUBjbHVzdGVyMG4ubnpsZHhkeS5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5JmFwcE5hbWU9Q2x1c3RlcjBO
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  labels:
    app: backend-api
    tier: backend
type: Opaque
data:
  # Replace <your-base64-encoded-jwt-secret> with your actual base64 encoded JWT secret
  # To encode: echo -n "your-jwt-secret" | base64
  jwt-secret: eW91cl9qd3Rfc2VjcmV0X2tleQ==
