apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: three-tier
  labels:
    app: frontend
    tier: frontend
data:
  # Environment
  NODE_ENV: "production"

  # API Configuration
  API_URL: "https://notesflow.himanshubhatt.co.in/api"
