apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  labels:
    app: frontend
    tier: frontend
data:
  # Environment
  NODE_ENV: "production"

  # API Configuration
  VITE_API_URL: "/notesflow/api" # Updated to match the Ingress path
