apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: frontend
          image: ${ECR_REPO1}:latest # This will be replaced by actual ECR URL
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            # ConfigMap Values
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: NODE_ENV
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: REACT_APP_API_URL
            - name: REACT_APP_TITLE
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: REACT_APP_TITLE
            - name: REACT_APP_DESCRIPTION
              valueFrom:
                configMapKeyRef:
                  name: frontend-config
                  key: REACT_APP_DESCRIPTION
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          startupProbe:
            httpGet:
              path: /
              port: http
            failureThreshold: 30
            periodSeconds: 10
